// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostSource } from "./CostSource";
import type { MessagePart } from "./MessagePart";
import type { MessageTokens } from "./MessageTokens";
import type { Role } from "./Role";

export type Message = {
  id: string;
  role: Role;
  agent: string | null;
  time_created: number;
  time_completed: number | null;
  mode: string | null;
  model: string | null;
  provider: string | null;
  tokens?: MessageTokens;
  cost: number;
  cost_source?: CostSource;
  parts: Array<MessagePart>;
  subagent_id?: string;
  nickname?: string;
  automated?: boolean;
};
