// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolState } from "./ToolState";

export type MessagePart =
  | { type: "text"; text: string; time_created: number }
  | { type: "reasoning"; text: string; time_created: number }
  | { type: "plan"; text: string; approval_status: string; time_created: number }
  | {
      type: "tool";
      tool: string;
      title?: string;
      callID?: string;
      state: ToolState;
      time_created: number;
    }
  | { type: "image"; url?: string; data?: string; mime_type?: string; time_created?: number };
