// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionReference } from "./SessionReference";

export type SessionFileActivity = {
  reference: SessionReference;
  projectIdentityKey: string;
  path: string;
  kind: string;
  count: number;
  latestTime: number;
};
