// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInfo } from "./AgentInfo";
import type { SessionHead } from "./SessionHead";

export type SessionIndex = { agents: Array<AgentInfo>; sessions: Array<SessionHead> };
