// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectIdentity } from "./ProjectIdentity";
import type { SessionReference } from "./SessionReference";
import type { SessionStats } from "./SessionStats";

export type SessionHead = {
  reference: SessionReference;
  title: string;
  directory: string;
  display_title?: string;
  parent_reference?: SessionReference;
  project_identity: ProjectIdentity;
  project_identity_resolver_revision?: string;
  project_identity_input_signature?: string;
  time_created: number;
  time_updated: number;
  stats: SessionStats;
  model_usage?: { [key in string]: number };
  smart_tags: Array<string>;
  smart_tags_source_updated_at?: number;
  smart_tags_classifier_revision?: string;
};
