// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolState = {
  status: string;
  input?: unknown;
  output?: unknown;
  error?: unknown;
  metadata?: unknown;
};
